Add writer to modernpython
alliander-opensource/pycgmes pull request #38
Opened 2024-10-28 23:31 UTC by tom-hg57

2025-01-31 14:15 UTC, guillaume-alliander requested changes
Mostly point of details. I do wonder about ruff which seems to not run on PR outside the main repo.

2025-01-31 14:15 UTC, guillaume-alliander commented on pycgmes/utils/profile.py
> +        order = list(self.__class__)
I think that this is invalid? `self.__class__`, is a type, which is not iterable. And I am not sure what is meant: `order=[self.__class__]`, or maybe `order=self.__class__.mro`?

2025-01-31 14:15 UTC, guillaume-alliander commented on pyproject.toml
Maybe the CI is not propely setup for a PR coming from another repo. 

Running it locally, I have a few errors. I suggest adding 

```toml
[tool.ruff.lint.per-file-ignores]
"{tests}/*" = [
    "PLR2004", # magic number are OK in tests
]
```

2025-01-31 14:15 UTC, guillaume-alliander commented on tests/test_shacl.py
>          with pytest.raises(ValueError):
```suggestion
        with pytest.raises(ValueError): # noqa: PT011 ValueErorr is exaclty what's raised
```

2025-02-06 22:43 UTC, tom-hg57 commented on pycgmes/utils/profile.py
> +    def __lt__(self, other):
This is correct. I added a docstring.

2025-02-06 22:47 UTC, tom-hg57 commented on pycgmes/utils/profile.py
> +        order = list(self.__class__)
`self.__class__` is not a normal class, but an enum class. Iterating an enum class provides the enum values in the order as they were defined.

2025-02-06 22:48 UTC, tom-hg57 commented on pyproject.toml
Good idea. I added the configuration.

2025-02-06 23:02 UTC, tom-hg57 commented
> Mostly point of details. I do wonder about ruff which seems to not run on PR outside the main repo.

It seems "ruff check --diff" is not working as I expected :( (as "ruff format --diff"). I changed it back to "ruff check --no-fix".

Part of the changes must actually be done in cimgen: https://github.com/sogno-platform/cimgen/pull/55

2025-02-10 15:12 UTC, guillaume-alliander commented
@tom-hg57 Thanks for the changes! There is one last thing which i did not notice and would like to automate at some point: `version` in pyproject.toml needs to be increased, to have a new version uploaded to pypi. Then happy to merge!

2025-02-11 00:30 UTC, tom-hg57 commented
> @tom-hg57 Thanks for the changes! There is one last thing which i did not notice and would like to automate at some point: `version` in pyproject.toml needs to be increased, to have a new version uploaded to pypi. Then happy to merge!

Done.

2025-02-13 23:18 UTC, tom-hg57 commented
I don't understand what is the status of this PR. I think I made all requested changes. But the status shows: "Requested changes must be addressed to merge this pull request." Should I re-request the review? But how?

2025-02-18 15:30 UTC, guillaume-alliander approved these changes
LGTM, thanks!

2025-02-18 15:56 UTC, merged